name: "Slither CI"

on: [push, pull_request]

env:
  NODE_VER: 16

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}
      - run: |
          echo -n "Node version: "
          node -v
          echo -n "Npm version: "
          npm -v
          npm i
      - name: slither
        id: slither
        run: |
          pip3 install slither-analyzer solc-select
          SOLCVER="$(solc-select install | tail -1)"
          solc-select install "$SOLCVER"
          solc-select use "$SOLCVER"
          slither --sarif results.sarif \
            --filter-paths "node_modules" \
            --checklist \
            --markdown-root "https://github.com/${GITHUB_REPOSITORY}/blob/${GITHUB_SHA}/" \
            '**/*.sol' > slither_report.md
      - name: Post SARIF findings in the pull request
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request' && (success() || failure())
        with:
          filePath: "slither_report.md"
      - uses: Ayrx/sarif_to_github_annotations@v0.2.2
        if: success() || failure()
        with:
          sarif_file: results.sarif
